### ISSUE TITLE
The switch statement needs to be more logically

### ISSUE THREAD

**Issue by huy-vuduc** [cvn-intern-2020/YumYum#167]
- https://github.com/cvn-intern-2020/YumYum/blob/master/src/client/reducers/alert.js#L10-L20
- https://github.com/cvn-intern-2020/YumYum/blob/master/src/client/reducers/group.js#L25-L38

I think it's better to use break keyword in the switch statement. Without the break statement, additional blocks may be executed if the evaluation matches the case value.

In other words when a match is found, and the job is done, if the break statement is encountered. Otherwise the switch statement will continue evaluating the expression.

Please consider other places, too.

**Comment by lamnguyencse17** [comment]
> switch (action.type) {
    case SET_ALERT: {
      let { message, type } = action.payload;
      return { message, type, showAlert: true };
    }
    case HIDE_ALERT: {
      return { ...initialState };
    }
    default:
      return state;
  }

Quoted from one of the files you mentioned, `switch case` is already using `return` statement which is stronger than `break`. and Redux requires `return` to update the states

**Comment by huy-vuduc** [comment]
I understood your concept. 
It's OK with "return" in the switch statement
